version: '2'

volumes:
  business-central_repositories:
    driver: local
  business-central_controller:
    driver: local
  business-central_userdata:
    driver: local
  h2database_data:
    driver: local
  kie-server_userdata:
    driver: local
  kie-server_mvn:
    driver: local
  kafka_data:
    driver: local
  elasticsearch_data:
    driver: local
  mockserver_expectations:
    driver: local
  apromore_config:
    driver: local
  apromore_events:
    driver: local
  apromore_database:
    driver: local

services:
  business-central:
    hostname: business-central-host
    image: jizuzquiza/business-central:1.0-7.56.0.Final
    profiles: ["designer","runtime","runtime-with-events","runtime-cluster","process-instance-migration","all"]
    volumes:
      - business-central_repositories:/opt/jboss/repositories
    ports:
    - 8081:8080
    - 8001:8001
    mem_limit: 2500m
  h2database:
    hostname: h2database-host
    image: jizuzquiza/h2database:1.0
    profiles: ["runtime","runtime-with-events","runtime-cluster","process-instance-migration","all"]
    volumes:
    - h2database_data:/opt/h2/data
    ports:
    - 8082:8082
    mem_limit: 400m
  kie-server-1:
    hostname: kie-server-host-1
    image: jizuzquiza/kie-server:1.0-7.56.0.Final
    profiles: ["runtime","runtime-with-events","runtime-cluster","process-instance-migration","all"]
    environment:
      BC_MAVEN_REPO_USER: jbpmAdmin
      BC_MAVEN_REPO_PASSWORD: password@1
      BC_MAVEN_REPO: http://business-central-host:8080/business-central/maven2
      EXTRA_OPTS: > 
        -Dorg.kie.server.id=jbpm-development-server
        -Dorg.kie.server.location=http://kie-server-host-1:8080/kie-server/services/rest/server
        -Dorg.kie.server.controller=http://business-central-host:8080/business-central/rest/controller
        -Dorg.kie.server.controller.user=controllerUser
        -Dorg.kie.server.controller.pwd=password@1
        -Dorg.jbpm.task.cleanup.enabled=true
        -Dorg.kie.prometheus.server.ext.disabled=true
        -Dorg.jbpm.event.emitters.elasticsearch.url=http://elasticsearch-host:9200
        -Dorg.kie.executor.retry.count=0
        -Dorg.kie.executor.interval=10
        -Dorg.kie.kafka.server.ext.disabled=false
        -Dorg.kie.server.jbpm-kafka.ext.bootstrap.servers=kafka-host:9092
        -Dorg.kie.server.jbpm-kafka.ext.client.id=kie-server-kafka-client-1
        -Dorg.kie.server.jbpm-kafka.ext.group.id=business-automation-platform-kie-server-consumer-1
        -Dorg.kie.dmn.runtime.listeners.mylistener=com.business.platform.drools.dmn.event.listener.ElasticsearchDmnEventListener
#       -Dorg.kie.server.bypass.auth.user=true
        -DAPP_COUNTRY=local
      JAVA_OPTS: -Xms1024m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=368m -Djava.net.preferIPv4Stack=true
    ports:
    - 8080:8080
    - 8787:8787
    depends_on:
    - h2database
    mem_limit: 1800m
  kie-server-2:
    hostname: kie-server-host-2
    image: jizuzquiza/kie-server:1.0-7.56.0.Final
    profiles: ["runtime-cluster"]
    environment:
      BC_MAVEN_REPO_USER: jbpmAdmin
      BC_MAVEN_REPO_PASSWORD: password@1
      BC_MAVEN_REPO: http://business-central-host:8080/business-central/maven2
      EXTRA_OPTS: >
        -Dorg.kie.server.id=jbpm-development-server
        -Dorg.kie.server.location=http://kie-server-host-2:8080/kie-server/services/rest/server
        -Dorg.kie.server.controller=http://business-central-host:8080/business-central/rest/controller
        -Dorg.kie.server.controller.user=controllerUser
        -Dorg.kie.server.controller.pwd=password@1
        -Dorg.jbpm.task.cleanup.enabled=true
        -Dorg.kie.prometheus.server.ext.disabled=true
        -Dorg.jbpm.event.emitters.elasticsearch.url=http://elasticsearch-host:9200
        -Dorg.kie.executor.retry.count=0
        -Dorg.kie.executor.interval=10
        -Dorg.kie.kafka.server.ext.disabled=false
        -Dorg.kie.server.jbpm-kafka.ext.bootstrap.servers=kafka-host:9092
        -Dorg.kie.server.jbpm-kafka.ext.client.id=kie-server-kafka-client-2
        -Dorg.kie.server.jbpm-kafka.ext.group.id=business-automation-platform-kie-server-consumer-2
      JAVA_OPTS: -Xms1024m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=368m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    ports:
    - 8086:8080
    - 8087:8087
    depends_on:
    - h2database
    mem_limit: 1800m
  zookeeper:
    hostname: zookeeper-host
    image: wurstmeister/zookeeper:3.4.6
    profiles: ["runtime","runtime-with-events","runtime-cluster","all"]
    ports:
    - 2181:2181
    mem_limit: 400m
  kafka:
    hostname: kafka-host
    image: wurstmeister/kafka:2.12-2.2.1
    profiles: ["runtime","runtime-with-events","runtime-cluster","all"]
    ports:
    - 9092:9092
    - 29092:29092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-host
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-host:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - kafka_data:/kafka
    depends_on:
    - zookeeper
    mem_limit: 768m
  kafdrop:
    hostname: kafdrop-host
    image: obsidiandynamics/kafdrop
    profiles: ["runtime-with-events","all"]
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka-host:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    mem_limit: 150m
  mockserver:
    hostname: mockserver-host
    profiles: ["mockserver","all"]
    image: mockserver/mockserver:mockserver-5.11.1
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/expectations.json
    volumes:
    - type: bind
      source: "."
      target: "/config"
    mem_limit: 200m
  castlemock:
    hostname: castlemock-host
    profiles: ["castlemock","all"]
    image: castlemock/castlemock:1.55
    ports:
      - 1082:8080
    mem_limit: 1000m
  jbpm-process-instance-migration:
    hostname: jbpm-process-instance-migration-host
    image: jizuzquiza/jbpm-process-instance-migration:1.0-7.56.0.Final
    profiles: ["process-instance-migration","all"]
    environment:
      KIE_VERSION: 7.56.0.Final
    ports:
    - 8090:8090
    depends_on:
    - kie-server-1
    mem_limit: 768m
  jbpm-xes-exporter:
    hostname: jbpm-xes-exporter-host
    image: jizuzquiza/jbpm-xes-exporter:1.0
    profiles: ["process-mining","all"]
    environment:
      database_driver: org.h2.Driver
      database_url: jdbc:h2:tcp://h2database-host/~/../opt/h2/data/jbpm-runtime-db
      database_user: sa
      database_password: sa
    ports:
    - 8089:8089
    mem_limit: 900m
  elasticsearch:
    hostname: elasticsearch-host
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    profiles: ["runtime-with-events","process-monitoring","all"]
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data:rw
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    ports:
    - 9200:9200
    - 9300:9300
    mem_limit: 2200m
  kibana:
    hostname: kibana-host
    image: docker.elastic.co/kibana/kibana:7.13.1
    profiles: ["dashboard-authoring","process-monitoring","all"]
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
    mem_limit: 1200m
  apromore-app:
    hostname: apromore-app-host
    image: jizuzquiza/apromore-app:1.0
    profiles: ["process-mining","all"]
    environment:
      JAVA_OPTS: "-server -Xmx8g -Xmn1g"
    volumes:
    - apromore_config:/opt/apromore/virgo-tomcat-server-3.6.4.RELEASE/repository/usr
    - apromore_events:/opt/apromore/Event-Logs-Repository
    ports:
    - 8084:9000
    depends_on:
    - h2database
    - apromore-database
    mem_limit: 4096m
  apromore-database:
    hostname: apromore-database-host
    image: jizuzquiza/apromore-database:1.0
    profiles: ["process-mining","all"]
    command: --max_allowed_packet=2G
    environment:
      MYSQL_DATABASE: apromore
      MYSQL_ROOT_PASSWORD: MAcri
      MYSQL_USER: apromore
      MYSQL_PASSWORD: MAcri
    volumes:
    - apromore_database:/var/lib/mysql
    ports:
     - 3306:3306
    mem_limit: 768m
