version: '2'

volumes:
  business-central_repositories:
    driver: local
  business-central_controller:
    driver: local
  business-central_userdata:
    driver: local
  h2database_data:
    driver: local
  kie-server_userdata:
    driver: local
  kie-server_mvn:
    driver: local
  elasticsearch_data:
    driver: local

services:
  business-central:
    hostname: business-central-host
    image: jizuzquiza/business-central:1.0
    volumes:
      - business-central_repositories:/opt/jboss/repositories
    ports:
    - 8081:8080
    - 8001:8001
    mem_limit: 2500m
  h2database:
    hostname: h2database-host
    image: jizuzquiza/h2database:1.0
    volumes:
    - h2database_data:/opt/h2/data
    ports:
    - 8082:8082
    mem_limit: 400m
  kie-server:
    hostname: kie-server-host
    image: jizuzquiza/kie-server:1.0
    environment:
      BC_MAVEN_REPO_USER: jbpmAdmin
      BC_MAVEN_REPO_PASSWORD: password@1
      BC_MAVEN_REPO: http://business-central-host:8080/business-central/maven2
    ports:
    - 8080:8080
    depends_on:
    - h2database
    - business-central
    mem_limit: 2100m
  jbpm-process-instance-migration:
    hostname: jbpm-process-instance-migration-host
    image: jizuzquiza/jbpm-process-instance-migration:1.0
    environment:
      KIE_VERSION: 7.54.0.Final
    ports:
    - 8090:8090
    depends_on:
    - kie-server
    mem_limit: 768m
  elasticsearch:
    hostname: elasticsearch-host
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    ports:
    - 9200:9200
    - 9300:9300
    mem_limit: 2200m
  kibana:
    hostname: kibana-host
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
    - 5601:5601
    mem_limit: 1200m
