FROM openjdk:8-jdk-alpine

COPY ./jbpm-process-xes-exporter/target/jbpm-process-xes-exporter-1.0.0-SNAPSHOT.jar jbpm-process-xes-exporter-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","./jbpm-process-xes-exporter-1.0.0-SNAPSHOT.jar"]
